grpc:
  port: 9000
  enableReflection: true
  client:
    grpcItemService:
      address: static://localhost:9000
      negotiation-type: plaintext
    grpcUserService:
      address: static://localhost:9000
      negotiation-type: plaintext
server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgresql
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
        use_sql_comments: false
    show_sql: false
  sql:
    init:
      platform: postgres